---
- name: Ensure lazygit is installed
  block:
    - name: Import installed lazygit version check
      ansible.builtin.include_tasks: noauto_check_installed_version.yml
      when: lazygit_installed_version is not defined

    - name: Force install if the version numbers do not match
      ansible.builtin.set_fact:
        lazygit_force_install: true
      when:
        - lazygit_installed_version is defined
        - lazygit_installed_version != lazygit_version

    - name: Install lazygit from source
      when: lazygit_installed_version is not defined or lazygit_force_install
      block:
        - name: Uninstall current lazygit installation
          ansible.builtin.include_tasks: noauto_uninstall.yml
          when: lazygit_installed_version is defined and lazygit_installed_version != ""

        - name: Download lazygit
          ansible.builtin.get_url:
            url: "{{ lazygit_download_url }}"
            dest: "{{ lazygit_download_dir }}/{{ lazygit_archive_name }}"
            mode: "0600"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
          become: true

        - name: Ensure lazygit installation folder exists
          ansible.builtin.file:
            path: "{{ lazygit_install_path }}"
            state: directory
            mode: "0755"
            owner: root
            group: root
          become: true

        - name: Extract archive
          ansible.builtin.unarchive:
            src: "{{ lazygit_download_dir }}/{{ lazygit_archive_name }}"
            dest: "{{ lazygit_install_path }}"
            remote_src: true
            creates: "{{ lazygit_install_path }}/lazygit"
          become: true

        - name: Create lazygit symlink
          ansible.builtin.file:
            src: "{{ lazygit_install_path }}/lazygit"
            dest: "/usr/local/bin/lazygit"
            state: link
            force: true
            mode: "0755"
            owner: root
            group: root
          become: true

        - name: Remove archive
          ansible.builtin.file:
            path: "{{ lazygit_download_dir }}/{{ lazygit_archive_name }}"
            state: absent
          become: true
