---
- name: Check installed lazygit version
  block:
    - name: Get installed lazygit version
      ansible.builtin.command:
        cmd: "lazygit --version"
      ignore_errors: true
      changed_when: false
      failed_when: false
      register: lazygit_installed_version_cmd

    - name: Extract only the version into a variable
      ansible.builtin.set_fact:
        lazygit_installed_version: "{{ (lazygit_installed_version_cmd.stdout | regex_search('version=([\\d.]+)', '\\1'))[0] | default('') }}"

    - name: Debug installed lazygit version
      ansible.builtin.debug:
        var: lazygit_installed_version
